security:
  encoders:
    App\Entity\Utilisateur:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Utilisateur


  firewalls:
    dev:
        pattern: ^/(_(profiler|wdt)|css|images|js)/
        security: false
    main:
        anonymous: true
        lazy: true
        provider: app_user_provider
        guard:
          authenticators:
            - App\Security\AppAuthenticator
        logout:
          path: app_logout
          target: /login
          # where to redirect after logout
          # target: app_any_route
        remember_me:
          secret: '%kernel.secret%'
          lifetime: 6048008
          path: /

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#firewalls-authentication

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, role: ROLE_USER }
    - { path: ^/gestion_ville, roles: ROLE_ADMIN }
    - { path: ^/gestion_lieu, roles: ROLE_ADMIN }
    - { path: ^/orgnaisateur, roles: ROLE_ORGA}
    - { path: ^/utilisateur, roles: ROLE_USER }

  role_hierarchy:
    ROLE_ORGA : ROLE_USER
    ROLE_ADMIN : ROLE_ORGA
